### ISSUE TITLE
It takes too long time to resolve functions.

### ISSUE THREAD

**Issue by xwlin222** [duo-labs/idapython#1]
Hi, all.
It's a good script to help reversing Arm firmware.
But sometimes it takes too long time to resolve functions and stop response in small firmwares.
I'm in `IDA Pro 7.0` environment.
![image](https://user-images.githubusercontent.com/15721702/33539610-486dee32-d902-11e7-85a7-92c27f5c7b11.png)
Any idea to solve this?

**Comment by todd-manning** [comment]
Hello - 
I haven't experienced this taking a long time. On the firmwares I've tested, the entire firmware conversion process for a typical 256k firmware image takes less than 3 minutes or so.

The code was developed on IDA 6.95. I'll upgrade the development system to IDA 7 and see if there's anything I can see happening. 

Care to share an example firmware that takes a long time to process? Do you have any information about how long it takes. Does it get to a situation where it never stops?

**Comment by XingweiLin** [comment]
Hi,
This firmware is a little endian `Arm`, `Arm-v7M` binary.
Its base address is `0x8000000`.
When I load it in the `IDA`, my script is:
```
from cortex_m_firmware import *
cortex = CortexMFirmware()
cortex.annotate_vector_table(0x8000000)
cortex.find_functions()
```

> Do you have any information about how long it takes. Does it get to a situation where it never stops?

No, it never stops until I press `cancel` button.

[test_bin.zip](https://github.com/duo-labs/idapython/files/1529465/test_bin.zip)

**Comment by todd-manning** [comment]
Thanks for the report. In my IDA 6.95 environment, this binary does indeed import. I'll upgrade my system to IDA 7 and figure out the issue here.

**Comment by XingweiLin** [comment]
Actually, when I press `cancel` button to stop the analysis process, it does be able to disassemble more functions.
But I don't know if it has done the analysis.

**Comment by XingweiLin** [comment]
Hi, all.
Have you test the plugin in the `IDA Pro7.x` environment?

**Comment by raomin** [comment]
Same here. IDA Pro 7.1, ARMv6, 120Ko firmware. After 10 min running still nothing...When I 'cancel', a bunch of function is identified.
Any chance you can confirm (and fix) this on 7.1?

Thanks for your helpful script.

**Comment by todd-manning** [comment]
To give updates to folks: I have used this plugin in an IDA 7+ environment. The firmware files I've tested against have not had similar issues, but I was able to repro slowness with one example provided by a user. @raomin, are you able to share the firmware you're having trouble with?

Thanks.
-t.

**Comment by todd-manning** [comment]
I just looked to see what might be up. I think I have a procedure that will work around this. I'm thinking it's related to the load address. I must be making some assumption in the code somewhere that it's loaded at 0x0 or something. I used the following a test firmware provided by @raomin, and while not 100% perfect, it performed the job basically instantly on IDA 7.1

idaapi.require("cortex_m_firmware")
c = cortex_m_firmware.CortexMFirmware()
c.annotate_vector_table(0x08000000)
c.find_functions()

I think the trick is to give annotate_vector_table() the address the firmware is actually loaded to. @XingweiLin can you try the above and let me know if that successfully works around the slowness issue you reported?

**Comment by todd-manning** [comment]
It looks like part of what's coming into play here is having a RAM section. I'm sure my code is doing something wrong. The case I tested @raomin's example firmware, I had only a ROM section, rebased to 0x08000000, with a size of exactly the size of the firmware; and with no RAM section. 

For me, that worked more-or-less as intended. The python script completed almost instantly. I will take a look at the specific case of having RAM. For now, I would suggest trying to use Cortex/Anmesia without having a RAM section included. It looks like the code must be trying to find code in the entire RAM section. In one case, it was 500MB in size, which might account for the slowness.

**Comment by todd-manning** [comment]
You could add the RAM section back after running the tools.
